# Generated by Django 2.1.3 on 2019-01-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adimn_name', models.CharField(max_length=255, verbose_name='管理员用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('req_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('req_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='注册ip')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次登录时间')),
                ('last_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='最后一次登录ip')),
                ('is_status', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员列表',
                'db_table': 'zhouju_admins',
            },
        ),
    ]
