# Generated by Django 2.1.3 on 2019-01-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='adimn_name',
            new_name='admin_name',
        ),
    ]
