# Generated by Django 2.1.3 on 2019-01-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.CharField(max_length=255, verbose_name='区id')),
                ('area', models.CharField(max_length=255, verbose_name='区')),
                ('cityid', models.CharField(max_length=255, verbose_name='市id')),
            ],
            options={
                'verbose_name': '全国区',
                'verbose_name_plural': '区列表',
                'db_table': 'zhouju_areas',
            },
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityid', models.CharField(max_length=255, verbose_name='市id')),
                ('city', models.CharField(max_length=255, verbose_name='市')),
                ('provinceid', models.CharField(max_length=255, verbose_name='省份id')),
            ],
            options={
                'verbose_name': '全国市',
                'verbose_name_plural': '城市列表',
                'db_table': 'zhouju_cities',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceid', models.CharField(max_length=255, verbose_name='省份id')),
                ('province', models.CharField(max_length=255, verbose_name='省份名称')),
            ],
            options={
                'verbose_name': '省份名称',
                'verbose_name_plural': '全国省份',
                'db_table': 'zhouju_provinces',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikename', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='邮箱')),
                ('is_status', models.BooleanField(default=True, verbose_name='状态')),
                ('reg_time', models.DateTimeField(max_length=255, null=True, verbose_name='注册时间')),
                ('reg_ip', models.CharField(max_length=255, null=True, verbose_name='注册IP')),
                ('last_time', models.DateTimeField(null=True, verbose_name='最后一次登录时间')),
                ('last_ip', models.CharField(max_length=255, null=True, verbose_name='最后一次登录ip')),
                ('id_card', models.CharField(max_length=255, null=True, unique=True, verbose_name='身份证号')),
                ('id_name', models.CharField(max_length=255, null=True, verbose_name='真实姓名')),
                ('is_student', models.BooleanField(default=False, verbose_name='是否报过名')),
                ('education', models.CharField(choices=[('wm', '文盲'), ('xx', '小学'), ('cz', '初中'), ('gz', '高中'), ('zz', '中专'), ('dz', '大专'), ('bk', '本科'), ('yjs', '研究生')], default='wm', max_length=11, null=True, verbose_name='学历')),
                ('dgree', models.CharField(choices=[('w', '无'), ('xs', '学士'), ('ss', '硕士'), ('bs', '博士')], default='w', max_length=11, null=True, verbose_name='学位')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='具体地址')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Citys')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Areas')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Provinces')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'db_table': 'zhouju_users',
            },
        ),
    ]
