# Generated by Django 2.1.3 on 2019-01-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='nikename',
            new_name='nickname',
        ),
    ]
