# Generated by Django 2.1.3 on 2019-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190115_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='专业'),
        ),
    ]
