# Generated by Django 2.1.3 on 2019-01-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_users_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='毕业院校'),
        ),
    ]
