# Generated by Django 2.1.3 on 2019-01-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_users_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_img',
            field=models.FileField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
